#pragma once
#include "ui/LauncherWindow.hpp"
#include <cassert>

namespace altrun {
struct NumericIntentRuntimeFixture {
    static void Run(App& app, HINSTANCE instance) {
        using classic_behavior::ContinuationEvidence;
        LauncherWindow window(app, instance);
        assert(window.Create());
        ShowWindow(window.hwnd_, SW_SHOW);
        SetActiveWindow(window.hwnd_);
        SetFocus(window.edit_);
        const auto prepare = [&] {
            window.CancelPendingNumericIntent();
            window.consumedNumericVirtualKey_ = 0;
            window.consumedNumericChar_ = 0;
            SetWindowTextW(window.edit_, L"v");
            SendMessageW(window.edit_, EM_SETSEL, 1, 1);
            window.lastTextInputTick_ = 0; // deliberate pause beyond 420ms
            LauncherResult first, second;
            first.id = L"first";
            second.id = L"second";
            window.results_ = {first, second};
            SendMessageW(window.edit_, WM_KEYDOWN, L'2', 1);
            assert(window.pendingNumericIntent_.active);
            window.pendingNumericIntent_.probeRequired = true;
            assert(window.CurrentQuery() == L"v");
            return window.pendingNumericIntent_.token;
        };
        auto token = prepare();
        // A char generated by the held key must not duplicate the pending digit.
        SendMessageW(window.edit_, WM_CHAR, L'2', 1);
        assert(window.CurrentQuery() == L"v");
        window.ApplyNumericContinuation(token, ContinuationEvidence::Present);
        assert(window.CurrentQuery() == L"v2" && !window.pendingNumericIntent_.active);
        assert(!window.immediateExecutionPending_);
        window.ApplyNumericContinuation(token, ContinuationEvidence::Absent);
        assert(window.CurrentQuery() == L"v2");

        token = prepare();
        SendMessageW(window.edit_, WM_KEYUP, L'2', 1);
        SendMessageW(window.edit_, WM_KEYDOWN, L'R', 1);
        SendMessageW(window.edit_, WM_CHAR, L'r', 1);
        assert(window.CurrentQuery() == L"v2r");
        window.ApplyNumericContinuation(token, ContinuationEvidence::Absent);
        assert(window.CurrentQuery() == L"v2r");

        token = prepare();
        window.pendingNumericIntent_.started -= classic_behavior::kNumericProbeBudgetMs;
        window.ExecutePendingNumericIntent();
        assert(window.CurrentQuery() == L"v2" && !window.pendingNumericIntent_.active);

        token = prepare();
        window.ApplyNumericContinuation(token - 1, ContinuationEvidence::Absent);
        assert(window.pendingNumericIntent_.active);
        // Existing result snapshots survive list reorder.
        window.results_.clear();
        assert(window.pendingNumericIntent_.result.id == L"second");
        window.pendingNumericIntent_.started -= classic_behavior::kNumericIntentGraceMs;
        window.ApplyNumericContinuation(token, ContinuationEvidence::Absent);
        assert(!window.pendingNumericIntent_.active && window.CurrentQuery() == L"v");

        token = prepare();
        SetWindowTextW(window.edit_, L"changed");
        window.ApplyNumericContinuation(token, ContinuationEvidence::Absent);
        assert(window.CurrentQuery() == L"changed" && !window.pendingNumericIntent_.active);

        token = prepare();
        SendMessageW(window.edit_, WM_KEYDOWN, VK_ESCAPE, 1);
        assert(!window.pendingNumericIntent_.active);
        window.ApplyNumericContinuation(token, ContinuationEvidence::Absent);
        assert(!IsWindowVisible(window.hwnd_));

        ShowWindow(window.hwnd_, SW_SHOW);
        SetActiveWindow(window.hwnd_);
        SetFocus(window.edit_);
        window.consumedNumericChar_ = 0;
        window.consumedNumericVirtualKey_ = 0;
        SetWindowTextW(window.edit_, L"vray");
        SendMessageW(window.edit_, EM_SETSEL, 1, 1);
        window.lastTextInputTick_ = 0;
        window.results_.resize(2);
        SendMessageW(window.edit_, WM_KEYDOWN, L'2', 1);
        SendMessageW(window.edit_, WM_CHAR, L'2', 1);
        assert(window.CurrentQuery() == L"v2ray" && !window.pendingNumericIntent_.active);
        DestroyWindow(window.hwnd_);
        MSG msg{};
        while (PeekMessageW(&msg, nullptr, WM_QUIT, WM_QUIT, PM_REMOVE)) {}
    }
};
}
